import numpy as np
a=np.matrix("1,2,3,4,5,6,7,8,9,10")
print(a)
print("----------------------------------------")
print(type(a))
print("----------------------------------------")
print(a.shape)
print("----------------------------------------")
print(a.shape[1])
print("----------------------------------------")
print(a.shape[0])
print("----------------------------------------")
print(a.size)
print("----------------------------------------")
#insert
col=np.matrix("2,3,4")
print(col)
print("----------------------------------------")
#addition
A= np.matrix(np.arange(0,20)).reshape(5,4)
B= np.matrix(np.arange(20,40)).reshape(5,4)
print("matrix A")
print(A)
print("----------------------------------------")
print("Matrix B")
print(B)
print("----------------------------------------")
print("add")
print(np.add(A,B))
print("----------------------------------------")
print("mul")
B=np.transpose(B)
print(np.dot(A,B))
print("----------------------------------------")
